## Clock Input (100 MHz from ZedBoard oscillator)
set_property PACKAGE_PIN Y9 [get_ports {CLK100MHZ}]
set_property IOSTANDARD LVCMOS33 [get_ports {CLK100MHZ}]
create_clock -add -name sys_clk -period 10.0 -waveform {0 5} [get_ports {CLK100MHZ}]
set_property PACKAGE_PIN F22 [get_ports {sw[0]}]
set_property PACKAGE_PIN G22 [get_ports {sw[1]}]
set_property PACKAGE_PIN H22 [get_ports {sw[2]}]
set_property PACKAGE_PIN F21 [get_ports {sw[3]}]
set_property PACKAGE_PIN H19 [get_ports {sw[4]}]
set_property PACKAGE_PIN H18 [get_ports {sw[5]}]
set_property PACKAGE_PIN H17 [get_ports {sw[6]}]
set_property PACKAGE_PIN M15 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]
set_property PACKAGE_PIN P16 [get_ports {btn[0]}]
set_property PACKAGE_PIN R16 [get_ports {btn[1]}]
set_property PACKAGE_PIN N15 [get_ports {btn[2]}]
set_property PACKAGE_PIN R18 [get_ports {btn[3]}]
set_property PACKAGE_PIN T18 [get_ports {btn[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[*]}]
set_property PULLDOWN TRUE [get_ports {btn[*]}]
set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property PACKAGE_PIN U21 [get_ports {led[3]}]
set_property PACKAGE_PIN V22 [get_ports {led[4]}]
set_property PACKAGE_PIN W22 [get_ports {led[5]}]
set_property PACKAGE_PIN U19 [get_ports {led[6]}]
set_property PACKAGE_PIN U14 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
## Buttons are async - don't check timing relative to clock
set_false_path -from [get_ports {btn[*]}]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
